services:
  db:
    ports:
      - 10099:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=MYDB2
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - /home/unreal/hack/authdb/postgres_datapart/:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: api
    ports:
      - 10098:8080
    environment:
      db-url: 'jdbc:postgres://db:5432/MYDB2'
      db-username: 'admin'
      db-password: 'admin'
    depends_on:
      - db
    restart: always
